version: "3.8"

services:
  db:
    image: postgres:15.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432 # PostgreSQLのデフォルトポートは5432
    volumes:
      - pgdata:/var/lib/postgresql/data # データを保存するボリューム
  api:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    tty: true # コンテナ内でコマンドを実行するために必要
    depends_on: # dbサービスが起動してからapiサービスを起動する
      - db
    build: # Dockerfileからイメージをビルドする
      context: ./api/
      dockerfile: Dockerfile
    ports: # ホストのポート3000をコンテナのポート3000にマッピングする　プロジェクトのルートディレクトリにあるapiディレクトリをコンテナの/appにマウントする
      - 3000:3000
    volumes: # ホストのディレクトリをコンテナにマウントする
      - ./api:/app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/usr/src/app
    command: "yarn dev"
    ports:
      - "8000:3000"
volumes:
  pgdata: